In [19]:
! pip install world_bank_data

Requirement already satisfied: world_bank_data in c:\users\cecilia\anaconda3\lib\site-packages (0.1.3)
Requirement already satisfied: pandas in c:\users\cecilia\anaconda3\lib\site-packages (from world_bank_data) (1.0.5)
Requirement already satisfied: requests in c:\users\cecilia\anaconda3\lib\site-packages (from world_bank_data) (2.24.0)
Requirement already satisfied: cachetools in c:\users\cecilia\anaconda3\lib\site-packages (from world_bank_data) (4.1.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas->world_bank_data) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas->world_bank_data) (1.18.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas->world_bank_data) (2020.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\cecilia\anaconda3\lib\site-packages (from requests->world_bank_data) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cecilia\anaconda3\lib\site-packages (from requests->world_bank_data) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\cecilia\anaconda3\lib\site-packages (from requests->world_bank_data) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\cecilia\anaconda3\lib\site-packages (from requests->world_bank_data) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\users\cecilia\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.6.1->pandas->world_bank_data) (1.15.0)

ERROR: unknown command "instal" - maybe you meant "install"

In [20]:
! pip install pandas_datareader

Collecting pandas_datareader
  Downloading pandas_datareader-0.9.0-py3-none-any.whl (107 kB)
Requirement already satisfied: requests>=2.19.0 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas_datareader) (2.24.0)
Requirement already satisfied: pandas>=0.23 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas_datareader) (1.0.5)
Requirement already satisfied: lxml in c:\users\cecilia\anaconda3\lib\site-packages (from pandas_datareader) (4.5.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\cecilia\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cecilia\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\cecilia\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\cecilia\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (1.25.9)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\cecilia\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.18.5)
Requirement already satisfied: six>=1.5 in c:\users\cecilia\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.6.1->pandas>=0.23->pandas_datareader) (1.15.0)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.9.0

In [47]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
from pprint import pprint
import world_bank_data as wb

In [48]:
base_url = "http://api.worldbank.org/v2/country/br?format=json"

In [49]:
response=requests.get(base_url).json()

In [50]:
pprint(response)

[{'page': 1, 'pages': 1, 'per_page': '50', 'total': 1},
 [{'adminregion': {'id': 'LAC',
                   'iso2code': 'XJ',
                   'value': 'Latin America & Caribbean (excluding high '
                            'income)'},
   'capitalCity': 'Brasilia',
   'id': 'BRA',
   'incomeLevel': {'id': 'UMC',
                   'iso2code': 'XT',
                   'value': 'Upper middle income'},
   'iso2Code': 'BR',
   'latitude': '-15.7801',
   'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
   'longitude': '-47.9292',
   'name': 'Brazil',
   'region': {'id': 'LCN',
              'iso2code': 'ZJ',
              'value': 'Latin America & Caribbean '}}]]

In [54]:
countries = wb.get_countries()
countries

,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
id,,,,,,,,,
ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.51670
AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.52280
AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,NaN,NaN
AGO,AO,Angola,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Luanda,13.2420,-8.81155
ALB,AL,Albania,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Tirane,19.8172,41.33170
...,...,...,...,...,...,...,...,...,...
XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,,Aggregates,Aggregates,,NaN,NaN
YEM,YE,"Yemen, Rep.",Middle East & North Africa,Middle East & North Africa (excluding high inc...,Low income,IDA,Sana'a,44.2075,15.35200
ZAF,ZA,South Africa,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Upper middle income,IBRD,Pretoria,28.1871,-25.74600
ZMB,ZM,Zambia,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IDA,Lusaka,28.2937,-15.39820
ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,Blend,Harare,31.0672,-17.83120

In [55]:
countries.to_csv("countries.csv")